"""DeepSeek prompt templates loaded from config/prompts/*.json."""

from app.prompts.prompt_loader import (
    hld_architecture_rules,
    prompt_expand_node,
    prompt_flowchart_generate,
    prompt_flowchart_update,
    prompt_hld_generate,
    prompt_hld_update,
    prompt_mindmap_generate,
    prompt_mindmap_update,
    prompt_sequence_generate,
    prompt_sequence_update,
    system_flowchart_generate,
    system_flowchart_update,
    system_hld_generate,
    system_hld_update,
    system_mindmap_expand,
    system_mindmap_generate,
    system_mindmap_update,
    system_sequence_generate,
    system_sequence_update,
)

__all__ = [
    "hld_architecture_rules",
    "prompt_expand_node",
    "prompt_flowchart_generate",
    "prompt_flowchart_update",
    "prompt_hld_generate",
    "prompt_hld_update",
    "prompt_mindmap_generate",
    "prompt_mindmap_update",
    "prompt_sequence_generate",
    "prompt_sequence_update",
    "system_flowchart_generate",
    "system_flowchart_update",
    "system_hld_generate",
    "system_hld_update",
    "system_mindmap_expand",
    "system_mindmap_generate",
    "system_mindmap_update",
    "system_sequence_generate",
    "system_sequence_update",
]
